---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-withnamespace-sept25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-withnamespace-sept25 
  name: test-withnamespace-sept25
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi